#!/bin/bash
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=0-00:30:00
#SBATCH --constraint=gpu
#SBATCH --mail-type=END,FAIL
#SBATCH --output=slurm_get_Hmm.out

module load vasp-tpc/6.4.2-gpu
module list
export OMP_NUM_THREADS=16
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
pwd
date
srun hostname
srun -n 1 -c 32 -G 1 --cpu-bind=cores --gpu-bind=none python gpu_compute_ewald_pot_sarc.py
date
