#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=6000
#SBATCH --time=0-10:00:00
#SBATCH --output=run_%a/slurm_191019_J7.5.out
#SBATCH --mail-type=END,FAIL
#SBATCH --array=0-79
#SBATCH --reservation=changroup_standingres

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
module list
pwd
date
srun hostname
cd "run_"$SLURM_ARRAY_TASK_ID
mpirun -np 32 python ./get_JM.py
cd ../
date


